target:
	cd lib/shm; make target
	cd lib/usb; make target
	cd lib/sem; make target
	cd gamepad; make target
	cd webserver/cgi-bin; make target
	@echo "Juw pils"

host:
	cd lib/shm; make host
	@echo "Juw pils"
