#!/bin/sh
#
# Start the gamepad program....
#
case "$1" in
start)
echo "Starting httpd..."
/usr/bin/gamepad.out
;;
stop)
echo -n "Stopping httpd..."
/usr/bin/killall gamepad.out
;;
restart|reload)
"$0" stop
"$0" start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit $?